// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var $$Array = require("bs-platform/lib/js/array.js");
var $$String = require("bs-platform/lib/js/string.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Day13$Adventofcode2019 = require("./day13.bs.js");

function readInput(param) {
  return Fs.readFileSync(__dirname + "/input", "utf8");
}

function solutionPart1(param) {
  var __x = Fs.readFileSync(__dirname + "/input", "utf8");
  return Day13$Adventofcode2019.Part1.make($$Array.map(Caml_format.caml_int_of_string, $$Array.of_list($$String.split_on_char(/* "," */44, __x))));
}

console.log("day13 part1", solutionPart1(/* () */0));

function solutionPart2(param) {
  var __x = Fs.readFileSync(__dirname + "/input", "utf8");
  return Day13$Adventofcode2019.Part2.make($$Array.map(Caml_format.caml_int_of_string, $$Array.of_list($$String.split_on_char(/* "," */44, __x))));
}

console.log("day13 part2", solutionPart2(/* () */0));

exports.readInput = readInput;
exports.solutionPart1 = solutionPart1;
exports.solutionPart2 = solutionPart2;
/*  Not a pure module */
