// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var $$String = require("bs-platform/lib/js/string.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Day09$Adventofcode2019 = require("./day09.bs.js");

function readInput(param) {
  return Fs.readFileSync(__dirname + "/input", "utf8");
}

function solutionPart1(param) {
  var func = Day09$Adventofcode2019.Part1.make;
  var arg = /* array */[1];
  var __x = Fs.readFileSync(__dirname + "/input", "utf8");
  return (function (param) {
                return Curry._2(func, param, arg);
              })($$Array.map(Caml_format.caml_int_of_string, $$Array.of_list($$String.split_on_char(/* "," */44, __x))))[1];
}

console.log("day09 part1", solutionPart1(/* () */0));

function solutionPart1$1(param) {
  var func = Day09$Adventofcode2019.Part1.make;
  var arg = /* array */[2];
  var __x = Fs.readFileSync(__dirname + "/input", "utf8");
  return (function (param) {
                return Curry._2(func, param, arg);
              })($$Array.map(Caml_format.caml_int_of_string, $$Array.of_list($$String.split_on_char(/* "," */44, __x))))[1];
}

console.log("day09 part2", solutionPart1$1(/* () */0));

exports.readInput = readInput;
exports.solutionPart1 = solutionPart1$1;
/*  Not a pure module */
