// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function solve(input) {
  return (input / 3 | 0) - 2 | 0;
}

var Part1 = {
  solve: solve
};

function solve$1(fuel) {
  var fuel$1 = solve(fuel);
  var match = fuel$1 > 0;
  if (match) {
    return fuel$1 + solve$1(fuel$1) | 0;
  } else {
    return 0;
  }
}

var Part2 = {
  solve: solve$1
};

exports.Part1 = Part1;
exports.Part2 = Part2;
/* No side effect */
