// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Day01$Adventofcode2019 = require("./day01.bs.js");

function readInput(param) {
  return Fs.readFileSync(__dirname + "/input", "utf8");
}

function solution(solveFn) {
  return Fs.readFileSync(__dirname + "/input", "utf8").split("\n").map((function (value) {
                  return Curry._1(solveFn, Caml_format.caml_int_of_string(value));
                })).reduce((function (acc, n) {
                return acc + n | 0;
              }), 0);
}

console.log(solution(Day01$Adventofcode2019.Part1.solve));

console.log(solution(Day01$Adventofcode2019.Part2.solve));

exports.readInput = readInput;
exports.solution = solution;
/*  Not a pure module */
