// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var $$Array = require("bs-platform/lib/js/array.js");
var Day06$Adventofcode2019 = require("./day06.bs.js");

function readInput(param) {
  return Fs.readFileSync(__dirname + "/input", "utf8");
}

function solution(param) {
  return Day06$Adventofcode2019.Part1.make($$Array.to_list(Fs.readFileSync(__dirname + "/input", "utf8").split("\n")));
}

console.log("day06 part1", solution(/* () */0));

function solutionPart2(param) {
  return Day06$Adventofcode2019.Part2.make($$Array.to_list(Fs.readFileSync(__dirname + "/input", "utf8").split("\n")));
}

console.log("day06 part2", solutionPart2(/* () */0));

exports.readInput = readInput;
exports.solution = solution;
exports.solutionPart2 = solutionPart2;
/*  Not a pure module */
