// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Day04$Adventofcode2019 = require("./day04.bs.js");

function readInput(param) {
  return Fs.readFileSync(__dirname + "/input", "utf8");
}

function solutionPart1(param) {
  var values = Fs.readFileSync(__dirname + "/input", "utf8").split("-");
  var match = Belt_Array.get(values, 0);
  var match$1 = Belt_Array.get(values, 1);
  if (match !== undefined && match$1 !== undefined) {
    return Day04$Adventofcode2019.Part1.make(Caml_format.caml_int_of_string(match), Caml_format.caml_int_of_string(match$1));
  } else {
    return 0;
  }
}

function solutionPart2(param) {
  var values = Fs.readFileSync(__dirname + "/input", "utf8").split("-");
  var match = Belt_Array.get(values, 0);
  var match$1 = Belt_Array.get(values, 1);
  if (match !== undefined && match$1 !== undefined) {
    return Day04$Adventofcode2019.Part2.make(Caml_format.caml_int_of_string(match), Caml_format.caml_int_of_string(match$1));
  } else {
    return 0;
  }
}

console.log("day04 part1", solutionPart1(/* () */0));

console.log("day04 part2", solutionPart2(/* () */0));

exports.readInput = readInput;
exports.solutionPart1 = solutionPart1;
exports.solutionPart2 = solutionPart2;
/*  Not a pure module */
