// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Day03$Adventofcode2019 = require("../src/day03/day03.bs.js");

Jest.describe("day03", (function () {
        Jest.testAll("part1 test", /* :: */[
              /* tuple */[
                /* tuple */[
                  "R8,U5,L5,D3",
                  "U7,R6,D4,L4"
                ],
                6
              ],
              /* :: */[
                /* tuple */[
                  /* tuple */[
                    "R75,D30,R83,U83,L12,D49,R71,U7,L72",
                    "U62,R66,U55,R34,D71,R55,D58,R83"
                  ],
                  159
                ],
                /* :: */[
                  /* tuple */[
                    /* tuple */[
                      "R98,U47,R26,D63,R33,U87,L62,D20,R33,U53,R51",
                      "U98,R91,D20,R16,D67,R40,U7,R15,U6,R7"
                    ],
                    135
                  ],
                  /* [] */0
                ]
              ]
            ], (function (param) {
                return Jest.Expect[/* toBe */2](param[1], Jest.Expect[/* expect */0](Day03$Adventofcode2019.Part1[/* solve */5](param[0])));
              }));
        return Jest.testAll("part2 test", /* :: */[
                    /* tuple */[
                      /* tuple */[
                        "R8,U5,L5,D3",
                        "U7,R6,D4,L4"
                      ],
                      30
                    ],
                    /* :: */[
                      /* tuple */[
                        /* tuple */[
                          "R75,D30,R83,U83,L12,D49,R71,U7,L72",
                          "U62,R66,U55,R34,D71,R55,D58,R83"
                        ],
                        610
                      ],
                      /* :: */[
                        /* tuple */[
                          /* tuple */[
                            "R98,U47,R26,D63,R33,U87,L62,D20,R33,U53,R51",
                            "U98,R91,D20,R16,D67,R40,U7,R15,U6,R7"
                          ],
                          410
                        ],
                        /* [] */0
                      ]
                    ]
                  ], (function (param) {
                      return Jest.Expect[/* toBe */2](param[1], Jest.Expect[/* expect */0](Day03$Adventofcode2019.Part2[/* solve */3](param[0])));
                    }));
      }));

/*  Not a pure module */
