// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Day04$Adventofcode2019 = require("../src/day04/day04.bs.js");

Jest.describe("day04 part1", (function () {
        Jest.test("test input 1", (function () {
                return Jest.Expect[/* toEqual */12](1, Jest.Expect[/* expect */0](Day04$Adventofcode2019.Part1[/* make */0](111111, 111111)));
              }));
        Jest.test("test input 2", (function () {
                return Jest.Expect[/* toEqual */12](0, Jest.Expect[/* expect */0](Day04$Adventofcode2019.Part1[/* make */0](223450, 223450)));
              }));
        return Jest.test("test input 3", (function () {
                      return Jest.Expect[/* toEqual */12](0, Jest.Expect[/* expect */0](Day04$Adventofcode2019.Part1[/* make */0](123789, 123789)));
                    }));
      }));

Jest.describe("day04 part2", (function () {
        Jest.test("test input 1", (function () {
                return Jest.Expect[/* toEqual */12](1, Jest.Expect[/* expect */0](Day04$Adventofcode2019.Part2[/* make */0](112233, 112233)));
              }));
        Jest.test("test input 2", (function () {
                return Jest.Expect[/* toEqual */12](0, Jest.Expect[/* expect */0](Day04$Adventofcode2019.Part2[/* make */0](123444, 123444)));
              }));
        return Jest.test("test input 3", (function () {
                      return Jest.Expect[/* toEqual */12](1, Jest.Expect[/* expect */0](Day04$Adventofcode2019.Part2[/* make */0](111122, 111122)));
                    }));
      }));

/*  Not a pure module */
