// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Day02$Adventofcode2019 = require("../src/day02/day02.bs.js");

Jest.describe("day01", (function () {
        return Jest.testAll("part1 test", /* :: */[
                    /* tuple */[
                      /* array */[
                        1,
                        0,
                        0,
                        0,
                        99
                      ],
                      /* array */[
                        2,
                        0,
                        0,
                        0,
                        99
                      ]
                    ],
                    /* :: */[
                      /* tuple */[
                        /* array */[
                          2,
                          3,
                          0,
                          3,
                          99
                        ],
                        /* array */[
                          2,
                          3,
                          0,
                          6,
                          99
                        ]
                      ],
                      /* :: */[
                        /* tuple */[
                          /* array */[
                            2,
                            4,
                            4,
                            5,
                            99,
                            0
                          ],
                          /* array */[
                            2,
                            4,
                            4,
                            5,
                            99,
                            9801
                          ]
                        ],
                        /* :: */[
                          /* tuple */[
                            /* array */[
                              1,
                              1,
                              1,
                              4,
                              99,
                              5,
                              6,
                              0,
                              99
                            ],
                            /* array */[
                              30,
                              1,
                              1,
                              4,
                              2,
                              5,
                              6,
                              0,
                              99
                            ]
                          ],
                          /* [] */0
                        ]
                      ]
                    ]
                  ], (function (param) {
                      return Jest.Expect[/* toEqual */12](param[1], Jest.Expect[/* expect */0](Day02$Adventofcode2019.Part1[/* solve */2](param[0])));
                    }));
      }));

/*  Not a pure module */
