// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Day05$Adventofcode2019 = require("../src/day05/day05.bs.js");

Jest.describe("day01", (function () {
        Jest.testAll("intcode v1 test", /* :: */[
              /* tuple */[
                /* array */[
                  1,
                  0,
                  0,
                  0,
                  99
                ],
                /* array */[
                  2,
                  0,
                  0,
                  0,
                  99
                ]
              ],
              /* :: */[
                /* tuple */[
                  /* array */[
                    2,
                    3,
                    0,
                    3,
                    99
                  ],
                  /* array */[
                    2,
                    3,
                    0,
                    6,
                    99
                  ]
                ],
                /* :: */[
                  /* tuple */[
                    /* array */[
                      2,
                      4,
                      4,
                      5,
                      99,
                      0
                    ],
                    /* array */[
                      2,
                      4,
                      4,
                      5,
                      99,
                      9801
                    ]
                  ],
                  /* :: */[
                    /* tuple */[
                      /* array */[
                        1,
                        1,
                        1,
                        4,
                        99,
                        5,
                        6,
                        0,
                        99
                      ],
                      /* array */[
                        30,
                        1,
                        1,
                        4,
                        2,
                        5,
                        6,
                        0,
                        99
                      ]
                    ],
                    /* [] */0
                  ]
                ]
              ]
            ], (function (param) {
                var match = Day05$Adventofcode2019.Part1[/* make */1](param[0], 0);
                return Jest.Expect[/* toEqual */12](param[1], Jest.Expect[/* expect */0](match[0]));
              }));
        Jest.test("part1 test", (function () {
                var match = Day05$Adventofcode2019.Part1[/* make */1](/* array */[
                      3,
                      0,
                      4,
                      0,
                      99
                    ], 10);
                return Jest.Expect[/* toEqual */12](/* array */[10], Jest.Expect[/* expect */0](match[1]));
              }));
        Jest.test("part1 test", (function () {
                var match = Day05$Adventofcode2019.Part1[/* make */1](/* array */[
                      1002,
                      4,
                      3,
                      4,
                      33
                    ], 0);
                return Jest.Expect[/* toEqual */12](/* array */[
                            1002,
                            4,
                            3,
                            4,
                            99
                          ], Jest.Expect[/* expect */0](match[0]));
              }));
        Jest.test("part2 test position equals 8", (function () {
                var match = Day05$Adventofcode2019.Part1[/* make */1](/* array */[
                      3,
                      9,
                      8,
                      9,
                      10,
                      9,
                      4,
                      9,
                      99,
                      -1,
                      8
                    ], 8);
                return Jest.Expect[/* toEqual */12](/* array */[1], Jest.Expect[/* expect */0](match[1]));
              }));
        Jest.test("part2 test position doesnt equal 8", (function () {
                var match = Day05$Adventofcode2019.Part1[/* make */1](/* array */[
                      3,
                      9,
                      8,
                      9,
                      10,
                      9,
                      4,
                      9,
                      99,
                      -1,
                      8
                    ], 10);
                return Jest.Expect[/* toEqual */12](/* array */[0], Jest.Expect[/* expect */0](match[1]));
              }));
        Jest.test("part2 test immediate equals 8", (function () {
                var match = Day05$Adventofcode2019.Part1[/* make */1](/* array */[
                      3,
                      3,
                      1108,
                      -1,
                      8,
                      3,
                      4,
                      3,
                      99
                    ], 8);
                return Jest.Expect[/* toEqual */12](/* array */[1], Jest.Expect[/* expect */0](match[1]));
              }));
        return Jest.test("part2 test immediate doesnt equal 8", (function () {
                      var match = Day05$Adventofcode2019.Part1[/* make */1](/* array */[
                            3,
                            3,
                            1108,
                            -1,
                            8,
                            3,
                            4,
                            3,
                            99
                          ], 10);
                      return Jest.Expect[/* toEqual */12](/* array */[0], Jest.Expect[/* expect */0](match[1]));
                    }));
      }));

/*  Not a pure module */
