// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Day04$Adventofcode2019 = require("../src/day04/day04.bs.js");

Jest.describe("day04 part1", (function (param) {
        Jest.test("test input 1", (function (param) {
                return Jest.Expect.toEqual(1, Jest.Expect.expect(Day04$Adventofcode2019.Part1.make(111111, 111111)));
              }));
        Jest.test("test input 2", (function (param) {
                return Jest.Expect.toEqual(0, Jest.Expect.expect(Day04$Adventofcode2019.Part1.make(223450, 223450)));
              }));
        return Jest.test("test input 3", (function (param) {
                      return Jest.Expect.toEqual(0, Jest.Expect.expect(Day04$Adventofcode2019.Part1.make(123789, 123789)));
                    }));
      }));

Jest.describe("day04 part2", (function (param) {
        Jest.test("test input 1", (function (param) {
                return Jest.Expect.toEqual(1, Jest.Expect.expect(Day04$Adventofcode2019.Part2.make(112233, 112233)));
              }));
        Jest.test("test input 2", (function (param) {
                return Jest.Expect.toEqual(0, Jest.Expect.expect(Day04$Adventofcode2019.Part2.make(123444, 123444)));
              }));
        return Jest.test("test input 3", (function (param) {
                      return Jest.Expect.toEqual(1, Jest.Expect.expect(Day04$Adventofcode2019.Part2.make(111122, 111122)));
                    }));
      }));

/*  Not a pure module */
