// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Day01$Adventofcode2019 = require("../src/day01/day01.bs.js");

Jest.describe("day01", (function (param) {
        Jest.testAll("part1 test", /* :: */[
              /* tuple */[
                12,
                2
              ],
              /* :: */[
                /* tuple */[
                  14,
                  2
                ],
                /* :: */[
                  /* tuple */[
                    1969,
                    654
                  ],
                  /* :: */[
                    /* tuple */[
                      100756,
                      33583
                    ],
                    /* [] */0
                  ]
                ]
              ]
            ], (function (param) {
                return Jest.Expect.toBe(param[1], Jest.Expect.expect(Day01$Adventofcode2019.Part1.solve(param[0])));
              }));
        return Jest.testAll("part2 test", /* :: */[
                    /* tuple */[
                      12,
                      2
                    ],
                    /* :: */[
                      /* tuple */[
                        14,
                        2
                      ],
                      /* :: */[
                        /* tuple */[
                          1969,
                          966
                        ],
                        /* :: */[
                          /* tuple */[
                            100756,
                            50346
                          ],
                          /* [] */0
                        ]
                      ]
                    ]
                  ], (function (param) {
                      return Jest.Expect.toBe(param[1], Jest.Expect.expect(Day01$Adventofcode2019.Part2.solve(param[0])));
                    }));
      }));

/*  Not a pure module */
