// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Day10$Adventofcode2019 = require("../src/day10/day10.bs.js");

Jest.describe("day01", (function (param) {
        Jest.test("part1 test", (function (param) {
                var input = /* array */[
                  ".#..#",
                  ".....",
                  "#####",
                  "....#",
                  "...##"
                ];
                var match = Day10$Adventofcode2019.Part1.make(input);
                return Jest.Expect.toBe("3,4", Jest.Expect.expect(match[0]));
              }));
        Jest.test("part1 test", (function (param) {
                var input = /* array */[
                  "......#.#.",
                  "#..#.#....",
                  "..#######.",
                  ".#.#.###..",
                  ".#..#.....",
                  "..#....#.#",
                  "#..#....#.",
                  ".##.#..###",
                  "##...#..#.",
                  ".#....####"
                ];
                var match = Day10$Adventofcode2019.Part1.make(input);
                return Jest.Expect.toBe("5,8", Jest.Expect.expect(match[0]));
              }));
        Jest.test("part2 test", (function (param) {
                var input = /* array */[
                  ".#..##.###...#######",
                  "##.############..##.",
                  ".#.######.########.#",
                  ".###.#######.####.#.",
                  "#####.##.#.##.###.##",
                  "..#####..#.#########",
                  "####################",
                  "#.####....###.#.#.##",
                  "##.#################",
                  "#####.##.###..####..",
                  "..######..##.#######",
                  "####.##.####...##..#",
                  ".#####..#.######.###",
                  "##...#.##########...",
                  "#.##########.#######",
                  ".####.#.###.###.#.##",
                  "....##.##.###..#####",
                  ".#.#.###########.###",
                  "#.#.#.#####.####.###",
                  "###.##.####.##.#..##"
                ];
                var match = Day10$Adventofcode2019.Part1.make(input);
                return Jest.Expect.toBe("11,13", Jest.Expect.expect(match[0]));
              }));
        return Jest.test("part2 test", (function (param) {
                      var input = /* array */[
                        ".#..##.###...#######",
                        "##.############..##.",
                        ".#.######.########.#",
                        ".###.#######.####.#.",
                        "#####.##.#.##.###.##",
                        "..#####..#.#########",
                        "####################",
                        "#.####....###.#.#.##",
                        "##.#################",
                        "#####.##.###..####..",
                        "..######..##.#######",
                        "####.##.####...##..#",
                        ".#####..#.######.###",
                        "##...#.##########...",
                        "#.##########.#######",
                        ".####.#.###.###.#.##",
                        "....##.##.###..#####",
                        ".#.#.###########.###",
                        "#.#.#.#####.####.###",
                        "###.##.####.##.#..##"
                      ];
                      var coords = Day10$Adventofcode2019.Part2.make(input);
                      var match = Caml_array.caml_array_get(coords, 2);
                      return Jest.Expect.toBe("12,2", Jest.Expect.expect(String(match[0]) + ("," + String(match[1]))));
                    }));
      }));

/*  Not a pure module */
