// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Day06$Adventofcode2019 = require("../src/day06/day06.bs.js");
var Day06_graph$Adventofcode2019 = require("../src/day06/day06_graph.bs.js");

Jest.describe("day06", (function (param) {
        Jest.test("part1 graph test", (function (param) {
                return Jest.Expect.toBe(42, Jest.Expect.expect(Day06_graph$Adventofcode2019.Part1.make(/* :: */[
                                    "COM)B",
                                    /* :: */[
                                      "B)C",
                                      /* :: */[
                                        "C)D",
                                        /* :: */[
                                          "D)E",
                                          /* :: */[
                                            "E)F",
                                            /* :: */[
                                              "B)G",
                                              /* :: */[
                                                "G)H",
                                                /* :: */[
                                                  "D)I",
                                                  /* :: */[
                                                    "E)J",
                                                    /* :: */[
                                                      "J)K",
                                                      /* :: */[
                                                        "K)L",
                                                        /* [] */0
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("part1 test", (function (param) {
                return Jest.Expect.toBe(42, Jest.Expect.expect(Day06$Adventofcode2019.Part1.make(/* :: */[
                                    "COM)B",
                                    /* :: */[
                                      "B)C",
                                      /* :: */[
                                        "C)D",
                                        /* :: */[
                                          "D)E",
                                          /* :: */[
                                            "E)F",
                                            /* :: */[
                                              "B)G",
                                              /* :: */[
                                                "G)H",
                                                /* :: */[
                                                  "D)I",
                                                  /* :: */[
                                                    "E)J",
                                                    /* :: */[
                                                      "J)K",
                                                      /* :: */[
                                                        "K)L",
                                                        /* [] */0
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        return Jest.test("part2 test", (function (param) {
                      return Jest.Expect.toBe(4, Jest.Expect.expect(Day06$Adventofcode2019.Part2.make(/* :: */[
                                          "COM)B",
                                          /* :: */[
                                            "B)C",
                                            /* :: */[
                                              "C)D",
                                              /* :: */[
                                                "D)E",
                                                /* :: */[
                                                  "E)F",
                                                  /* :: */[
                                                    "B)G",
                                                    /* :: */[
                                                      "G)H",
                                                      /* :: */[
                                                        "D)I",
                                                        /* :: */[
                                                          "E)J",
                                                          /* :: */[
                                                            "J)K",
                                                            /* :: */[
                                                              "K)L",
                                                              /* :: */[
                                                                "K)YOU",
                                                                /* :: */[
                                                                  "I)SAN",
                                                                  /* [] */0
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ])));
                    }));
      }));

/*  Not a pure module */
